---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: What is NetworkManager?
    - name: module-02
      label: What is nmstate?
    - name: module-03
      label: Dynamic IP configuration with DHCP
    - name: module-04
      label: Static IP configuration
    - name: module-05
      label: Activating the connection
    - name: module-06
      label: Configuring DNS
tabs:
  - name: ">_ root"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ rhel"
    port: 443
    path: /tty2
    user: rhel
    host: rhel
