---
virtualmachines:
  - name: "host1"
    subdomain: "lab"
    image: "rhel-9.5"
    memory: "2G"
    cores: 1
    image_size: "40G"
    consoles:
      - name: terminal-host1
        command: virtctl console host1
    packages:
      - git
      - cockpit
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default

  - name: "host2"
    subdomain: "lab"
    image: "rhel-9.5"
    memory: "2G"
    cores: 1
    image_size: "40G"

    packages:
      - git
      - cockpit
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
