---
virtualmachines:
  - name: "host1"
    #image: "rhel-9.5"
    image: "docker://quay.io/rhpds/poc-image-builder-cnv:centos-9-x86_64-mucloma"
    image_type: registry
    memory: "2G"
    cores: 1
    image_size: "40G"

    packages:
      - git
      - cockpit
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: cockpit
        ports:
          - port: 9090
            protocol: TCP
            targetPort: 9090
            name: cockpit
    routes:
      - name: cockpit
        host: cockpit
        service: cockpit
        targetPort: 9090
        tls: true
        tls_termination: Edge
